layout: sidebar
style: light # dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

highlighter: rouge

markdown: kramdown
kramdown:
  math_engine: mathjax

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars # pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:

social_media:
  linkedin: jeffreywardman
  stackoverflow: jeffreywardman

topics:
  # - name: Deep Learning
  #   web_url: https://github.com/topics/deep-learning
  #   image_url:
  # - name: Medical Imaging
  #   web_url: https://github.com/topics/medical-imaging
  #   image_url:
  # - name: Astrodynamics, Astronomy, Astrophysics
  #   web_url: https://github.com/topics/astrodynamics
  #   image_url:
